kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      automountServiceAccountToken: False
      volumes:
        - name: nginx
          configMap:
            name: nginx
            defaultMode: 0444
        - name: tls
          secret:
            secretName: "chtison.io"
            defaultMode: 0444
      containers:
        - name: nginx
          image: nginx:1-alpine
          volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx
            - mountPath: /usr/local/secrets/
              name: tls
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nginx
