kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      automountServiceAccountToken: False
      volumes:
        - name: html
          configMap:
            name: html
            defaultMode: 0444
        - name: nginx
          configMap:
            name: nginx
            defaultMode: 0444
      containers:
        - name: nginx
          image: nginx:1-alpine
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html
              readOnly: True
            - mountPath: /etc/nginx
              name: nginx
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 80
  selector:
    app: nginx
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.global-static-ip-name: chtison-io
spec:
  backend:
    serviceName: nginx
    servicePort: 443
  tls:
    - secretName: tls
